### ISSUE TITLE
regeneration error

### ISSUE THREAD

**Issue by hillonyechekwa** [afuh/rick-and-morty-api-node#16]
I'm having issues using this api in a react component. Every time i import the api with {getCharacter} i get this Reference Error: regenerationRuntime is not defined (what ever the hell that means) that crashes my app. what exactly is the content of the getCharacter because i know it's an object but of what exactly? Why I'm asking this is because i know the results from fetching the data from the api directly in my console give an object with two items (info and result) and then result is an array of objects. so what exactly is getCharacter an object of(an object of the fulfilled promise or the results array of objects

**Comment by afuh** [comment]
Hey, 
this is not an API, this is a wrapper that consumes the [https://rickandmortyapi.com/](https://rickandmortyapi.com/). It only fetches the API and returns the data. 

The "content" of the `getCharacter` method is the response of what you are requesting to the API, in this case `characters`. 

If you want to know more about it, please check the docs [here](https://rickandmortyapi.com/documentation)
