### ISSUE TITLE
info.next in page 2 of characters returning same page

### ISSUE THREAD

**Issue by httpassoca** [afuh/rick-and-morty-api-node#20]
req: https://rickandmortyapi.com/api/character?page=2
res: 
```
{
  info: {
    next: "https://rickandmortyapi.com/api/character?page=2",
    [...]
  },
  results: [...]
}
```

**Comment by afuh** [comment]
I can't really replicate this, everything looks good to me, could you be more specific? 
are you experiencing the issue using [this client](https://github.com/afuh/rick-and-morty-api-node)? or with the [REST api](https://github.com/afuh/rick-and-morty-api)?
