### ISSUE TITLE
Uncaught Error: Cannot find module 'https'

### ISSUE THREAD

**Issue by alastairkitchen** [afuh/rick-and-morty-api-node#22]
I'm getting the following error when i'm calling getEpisodes()

> Uncaught Error: Cannot find module 'https'
>     at webpackMissingModule (get.ts:1:1)
>     at ./node_modules/rickmortyapi/dist/index.js (get.ts:1:1)
>     at options.factory (react refresh:6:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at fn (hot module replacement:62:1)
>     at ./src/pages/episodes.tsx (characters.tsx:115:1)
>     at options.factory (react refresh:6:1)
>     at __webpack_require__ (bootstrap:24:1)
>     at fn (hot module replacement:62:1)
>     at ./src/App.tsx (bundle.js:17:73)
> 

clicking into the index.js stack trace takes me to the line

`import https from 'https'`

--

im using create react app, my package.json file

> {
>   "name": "rick-and-morty",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "@testing-library/jest-dom": "^5.16.5",
>     "@testing-library/react": "^13.4.0",
>     "@testing-library/user-event": "^13.5.0",
>     "@types/jest": "^27.5.2",
>     "@types/node": "^16.18.3",
>     "@types/react": "^18.0.25",
>     "@types/react-dom": "^18.0.9",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "react-router-dom": "^6.4.3",
>     "react-scripts": "5.0.1",
>     "rickmortyapi": "^1.0.0",
>     "sass": "^1.56.1",
>     "sass-mq": "^6.0.0",
>     "typescript": "^4.9.3",
>     "web-vitals": "^2.1.4"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject"
>   },
>   "eslintConfig": {
>     "extends": [
>       "react-app",
>       "react-app/jest"
>     ]
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> }

**Comment by afuh** [comment]
Hey, 
I believe that this is not directly related to this package, but to the fact that CRA uses [Webpack 5](https://github.com/facebook/create-react-app/issues/11756). 

anyway thanks for reporting, I'll revisit this client to make it more accessible.

Let me know if that helps!

**Comment by alastairkitchen** [comment]
Yes that is helpful thakyou! it is indeed related to the fact that Create React App is using Webpack 5.

To fix locally i am in the process of adding the missing polyfills, im using [react-app-rewired](https://www.npmjs.com/package/react-app-rewired) to add the packages to the webpack config, hopefully that'll do the trick.

More info on updating the create react app webpack.config using react-app-rewired - https://github.com/facebook/create-react-app/issues/11756#issuecomment-1001130053

**Comment by afuh** [comment]
Thanks for letting me know! and I'm glad you found a solution. I'm about to create a release that will probably fix this issue.
