### ISSUE TITLE
Episodes 'character' type error

### ISSUE THREAD

**Issue by alastairkitchen** [afuh/rick-and-morty-api-node#27]
Hello,  great job on the API, i've been using it for a personal project to create an app displaying rick and morty characters and episodes and i find it easy to use.

I have come across a bug - there seems to be a type error in the Episode interface found in[ interfaces.ts](https://github.com/afuh/rick-and-morty-api-node/blob/master/src/interfaces.ts)

the episode interface uses the name 'character' but the episodes schema uses 'characters', this causes a typescript error in my code when i use the Episode interface (see image attached)

<img width="940" alt="Screenshot 2022-12-08 at 16 15 14" src="https://user-images.githubusercontent.com/5919195/206501461-d0c8f074-c074-4d0a-aa34-d1fbd9dc6311.png">

**Comment by afuh** [comment]
Hey @alastairkitchen
thanks for letting me know!
