### ISSUE TITLE
wrong type

### ISSUE THREAD

**Issue by OlegSkar1** [afuh/rick-and-morty-api-node#30]
(https://github.com/afuh/rick-and-morty-api-node/blob/6a1184a3f6e013b351020069e621f4b7959d0b5f/src/interfaces.ts#L60)

valid type must be specified as a ```residents: string[]```

![image](https://user-images.githubusercontent.com/95995489/210109634-cdf1567c-272d-494a-918a-f5441ab4130f.png)

**Comment by afuh** [comment]
Thanks for letting me know
